// Mocks generated by Mockito 5.0.16 from annotations
// in gmail_alarm/test/settings_screen_widget_test.dart.
// Do not manually edit this file.

import 'package:gmail_alarm/model/gmail_api_wrapper.dart' as _i3;
import 'package:gmail_alarm/model/google_auth_client.dart' as _i4;
import 'package:gmail_alarm/View_Model/gmail_label_view_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GmailLabelViewModelIF].
///
/// See the documentation for Mockito's code generation for more information.
class MockGmailLabelViewModelIF extends _i1.Mock
    implements _i2.GmailLabelViewModelIF {
  MockGmailLabelViewModelIF() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GmailApiWrapperIF].
///
/// See the documentation for Mockito's code generation for more information.
class MockGmailApiWrapperIF extends _i1.Mock implements _i3.GmailApiWrapperIF {
  MockGmailApiWrapperIF() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GoogleAuthClientIF].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthClientIF extends _i1.Mock
    implements _i4.GoogleAuthClientIF {
  MockGoogleAuthClientIF() {
    _i1.throwOnMissingStub(this);
  }
}
